project:
  type: website
  output-dir: docs

website:
  title: "Hongsup Shin"
  navbar:
    right:
      - text: "About"
        file: about.qmd
      - text: "Publications"
        file: publications.qmd
      - icon: github
        href: https://github.com/hongsupshin
      - icon: linkedin
        href: https://www.linkedin.com/in/hongsupshin/
  site-url: "https://hongsupshin.github.io/"
  open-graph: true  
format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    # fontsize: 16px



