name: mlflow_tune
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.0
  - scikit-learn=1.2.0
  - mlflow=2.1.1
  - lightgbm=3.3.2
  - dask-ml
  - jupyterlab
  - watermark
  - pip
  - pip:
    - ray==2.3.0  